# Generated by Django 3.2 on 2022-04-24 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Headline',
        ),
    ]
